// src/routes/about/+page.svelte
<script lang="ts">
	export let data;
</script>

<p>
	Konst & Teknik is a digital design studio based in Stockholm, founded in 2006 by Mattias Jakobsson
	and <a href="https://harald.peter.stream">Peter Ström</a>.
</p>
<p>
	The studio works within a wide range of projects, often in the intersection of on- and offline,
	for both commercial and cultural commissioners. We design books, visual identities, typefaces, and
	develop websites, digital products and services. We also teach, give lectures and host events — on
	our own, or in close collaboration with fellow specialists.
</p>
<p>
	If you are interested in a collaboration, please contact us at <a
		href="mailto:info@konst-teknik.se"><em>info@konst-teknik.se</em></a
	>.
</p>
<p>Or reach out to one of us directly:</p>

<div>
	<div>
		<p>
			Mattias Jakobsson<br />
			<a href="mailto:mattias@konst-teknik.se"><em>mattias@konst-teknik.se</em></a><br />
			+46 702 644 238
		</p>
	</div>
	<div class="half contact">
		<p class="space-before">
			<a href="http://www.haraldpeter.se" target="_blank">Peter Ström</a><br />
			<a href="mailto:peter@konst-teknik.se"><em>peter@kon.st</em></a><br />
			+46 706 531 175
		</p>
	</div>
</div>

<p>
	Visitors and post are welcome to Konst & Teknik, <a
		href="http://www.rutgerfuchsgatan9.se"
		target="_blank">Rutger Fuchsgatan 9</a
	>, 11667 Stockholm, Sweden
</p>

// app/components/About.tsx
import s from "./About.module.scss";
import cn from 'classnames'
import { Image } from 'react-datocms'
import { Markdown } from "next-dato-utils/components";

type Props = {
  show: boolean
  about: AboutQuery['about']
  allCommisioners: AllCommisionersQuery['allCommisioners']
}

export default function About({ show, about, allCommisioners }: Props) {

  return (
    <div className={cn(s.about, show && s.show)}>
      <Image data={about.image?.responsiveImage} objectFit="cover" />
      <div className={s.content}>
        <Markdown content={about.intro} />
        <p>Or reach out to one of us directly:</p>
        <p>
          Mattias Jakobsson<br />
          <a href="mailto:mattias@konst-teknik.se"><em>mattias@konst-teknik.se</em></a><br />
          +46 702 644 238
        </p>
        <p>
          <a href="http://www.haraldpeter.se" target="_blank">Peter Ström</a><br />
          <a href="mailto:peter@konst-teknik.se"><em>peter@kon.st</em></a><br />
          +46 706 531 175
        </p>
        <p>
          Visitors and post are welcome to Konst & Teknik, <a
            href="http://www.rutgerfuchsgatan9.se"
            target="_blank"
            rel="noreferrer">Rutger Fuchsgatan 9</a
          >, 11667 Stockholm, Sweden
        </p>
        <h3>A selection of our commissioners</h3>
        <ul>
          {allCommisioners?.map((commisioner, i) =>
            <li key={i}>{commisioner.name}</li>
          )}
        </ul>
      </div>
    </div>
  )
}
